### ISSUE TITLE
No validation after adding a book

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#102]
Hi!

I'm continuing to add books of my library but since yesterday evening there is no validation any more! What I mean, is after validating the new book, the page doesn't reload. I still have the form and the different buttons (cancel, add, add + new).

I added books yesterday morning (2017-06-01) and it was still working normally. I have this issue with Firefox and Chrome on Android and with Firefox on Windows too.

**Comment by maxlath** [comment]
@thewholelifetolearn thanks for reporting, I'm looking at it

**Comment by maxlath** [comment]
sorry, it was due to a change in behavior introduced by [`7ed04ff`](https://github.com/inventaire/inventaire-client/commit/7ed04ffa5bf5639b8eb3bdcef892f717a48ec6d6#diff-3ae13cf0d629e6dcd9b1918e30238394), should now have been fixed by 278db4b: can you confirm?

**Comment by thewholelifetolearn** [comment]
Sorry it still doesn't work.  

I also realized that there are no more information about the book when adding it to the inventory. There only the buttons. Cover, title, authors, ... are not displayed any more.

![image](https://cloud.githubusercontent.com/assets/823564/26717384/7faf08c0-477d-11e7-81e6-db09365eff66.png)

**Comment by maxlath** [comment]
could it be that you still

**Comment by thewholelifetolearn** [comment]
I had emptied the cache before but it is now fixed.
